# Generated by Django 4.2.4 on 2024-09-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
